[workspace]
members = [".", "crates/shed_macros"]
resolver = "2"

[package]
name = "shed"
description = "A linux shell written in rust"
authors = ["Kyler Clay"]
license = "MIT"
repository = "https://github.com/km-clay/shed"
publish = false
version = "0.41.2"

edition = "2024"

[profile.release]
debug = true

[profile.dist]
inherits = "release"
debug = false
strip = true

[dependencies]
shed_macros = { path = "./crates/shed_macros" }
ariadne = "0.6.0"
bitflags = { version = "2.11.1", features = ["serde"] }
chrono = "0.4.44"
itertools = "0.14.0"
log = "0.4.29"
nix = { version = "0.31.2", features = ["uio", "term", "user", "resource", "hostname", "fs", "default", "signal", "process", "event", "ioctl", "poll", "net", "socket"] }
regex = "1.12.3"
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde_json = "1.0.149"
smallvec = { version = "1.15.1", features = ["serde", "write"] }
tempfile = "3.27.0"
unicode-segmentation = "1.13.2"
unicode-width = "0.2.2"
vte = "0.15"
yansi = "1.0.1"
stacker = "0.1.24"
rustc-hash = "2.1.2"
smol_str = "0.3.6"
bstr = "1.13.1"
hipstr = "0.8.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
tempfile = "3.27.0"

[[bin]]
name = "shed"
